import 'package:get_storage/get_storage.dart';
import 'package:image_picker/image_picker.dart';

String Loginphone = '';
String LoginStatus = '';
String Signupphone = '';
String Signupemail = '';
String Signupname = '';
final UserData = GetStorage();
String UserID = '';
String expiry = '';
String aadhar = '';
String pan = '';
String brand = '';
String model = '';
String year = '';
String licensePlate = '';
String registrationPlate = '';
String vehicleIdentificationNumber = '';
String chasisNumber = '';
String insuranceNumber = '';
String insuranceExpiryDate = '';
String vehicleInspection = '';
String vehicleInspectionExpiryDate = '';
XFile? drivingLicense1;
XFile? drivingLicense2;
XFile? aadharDetails1;
XFile? aadharDetails2;
XFile? panDetails1;
XFile? vehiclePictures1;
XFile? vehiclePictures2;
XFile? vehiclePictures3;
XFile? vehiclePictures4;
XFile? vehicleDocuments1;
XFile? vehicleDocuments2;
XFile? vehicleDocuments3;
XFile? vehicleDocuments4;
List<dynamic> OrderRequest = [];
Map<String, dynamic> loginData = {};
